// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGlQiD2XtLtWZ5OHTkztfcJQiN8nB7tmo',
    appId: '1:57604481514:web:777a839a6da79b48b61293',
    messagingSenderId: '57604481514',
    projectId: 'projeto-escola-22b2f',
    authDomain: 'projeto-escola-22b2f.firebaseapp.com',
    storageBucket: 'projeto-escola-22b2f.appspot.com',
    measurementId: 'G-4J502B5WBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqnpidHLXBsTlvVxtmEOkk_niKc9Bn_ws',
    appId: '1:57604481514:android:970b9c5d52a4a480b61293',
    messagingSenderId: '57604481514',
    projectId: 'projeto-escola-22b2f',
    storageBucket: 'projeto-escola-22b2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8D9iHyh4C92iEabtEJlasWnmtFnT0sXw',
    appId: '1:57604481514:ios:6f50ab46cc0baec2b61293',
    messagingSenderId: '57604481514',
    projectId: 'projeto-escola-22b2f',
    storageBucket: 'projeto-escola-22b2f.appspot.com',
    iosBundleId: 'com.example.escola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8D9iHyh4C92iEabtEJlasWnmtFnT0sXw',
    appId: '1:57604481514:ios:ec19fd181b7a305cb61293',
    messagingSenderId: '57604481514',
    projectId: 'projeto-escola-22b2f',
    storageBucket: 'projeto-escola-22b2f.appspot.com',
    iosBundleId: 'com.example.escola.RunnerTests',
  );
}
